### ISSUE TITLE
Make it much easier to plug in different message-receiving services

### ISSUE THREAD

**Issue by stkent** [stkent/GooglePlayRatingsReporter#3]
Right now, there's a bunch of HipChat hardcoding. We should make it easier to add new message-receiving service modules by interacting with them via a single interface.

**Comment by stkent** [comment]
See https://pymotw.com/2/abc/

**Comment by macklinu** [comment]
Good call. How would you want to invoke the script and differentiate between the services?

If the executable main script was named `main.py` for this example, perhaps something like:

```bash
$ python main.py --message-service=slack --config=/path/to/configuration.json
```

**Comment by stkent** [comment]
I think ^ is probably as good as we'll get, though it will likely involve some unavoidable stringly typed code. Probably better than requiring manipulation of the script itself to change services, however.

**Comment by stkent** [comment]
At the moment, the configuration file contains HipChat-specific information (in particular, the room name). As such, we'd probably need to include the receiving messaging services in the configuration file also. Trying to think of a good structure that doesn't involve a lot of duplication...

**Comment by stkent** [comment]
Maybe something like this?

```json
{
    "services": [
        "slack",
        "hipchat"
    ],
    "apps": [
        {
            "name": "App 1",
            "scrape_url": "https://play.google.com/store/apps/details?id=com.example.app1&hl=en",
            "channels": {
                "slack": "slack-channel-name-app-1",
                "hipchat": "hipchat-channel-name-app-1"
            }
        },
        {
            "name": "App 2",
            "scrape_url": "https://play.google.com/store/apps/details?id=com.example.app2&hl=en",
            "channels": {
                "slack": "slack-channel-name-app-2",
            }
        }
    ]
}
```

That way it's easy to switch an entire channel on/off, or to control reporting per-channel (by omitting an entry from the channels object). Thoughts?

**Comment by macklinu** [comment]
Yeah, I like this approach more. Nice.

In terms of the this spec, should our slack channel names include the `#` symbol? I guess we'll find out when we work more with the Slack API, but that just popped into my head. :smile:

**Comment by stkent** [comment]
Good thought on the `#` - no idea, but will keep it in mind, thanks!
